---
- name: Create Prometheus user
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create Prometheus directories
  file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
  loop:
    - /etc/prometheus
    - /var/lib/prometheus

- name: Download Prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Install Prometheus binaries
  copy:
    src: "/tmp/prometheus-2.51.2.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
    remote_src: yes
  loop:
    - prometheus
    - promtool

- name: Install Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus

- name: Create Prometheus systemd service
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus Monitoring Server
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus
      User=prometheus
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: restarted
