{
 "title": "Spring Petclinic Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "timeRange",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{ status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "HTTP Request Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "request - ok"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=~\"5..\"}[1m]))",
     "legendFormat": "request - err"
    }
   ]
  },
  {
   "title": "Owners Updated",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(petclinic_owner_seconds_count{method=\"updateOwner\", exception=\"none\"})"
    }
   ]
  },
  {
   "title": "Owners Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(petclinic_owner_seconds_count{method=\"createOwner\", exception=\"none\"})"
    }
   ]
  },
  {
   "title": "Pets Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(petclinic_pet_seconds_count{method=\"processCreationForm\", exception=\"none\"})"
    }
   ]
  },
  {
   "title": "Visit Created",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(petclinic_visit_seconds_count{method=\"read\", exception=\"none\"})"
    }
   ]
  },
  {
   "title": "SPC Business Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(petclinic_owner_seconds_count{method=\"createOwner\", exception=\"none\"})",
     "legendFormat": "owner create"
    },
    {
     "expr": "sum(petclinic_pet_seconds_count{method=\"processCreationForm\", exception=\"none\"})",
     "legendFormat": "pet create"
    },
    {
     "expr": "sum(petclinic_visit_seconds_count{method=\"create\", exception=\"none\"})",
     "legendFormat": "visit create"
    },
    {
     "expr": "sum(petclinic_owner_seconds_count{method=\"updateOwner\", exception=\"none\"})",
     "legendFormat": "owner update"
    }
   ]
  }
 ]
}