#!/usr/bin/env bash
# join-worker-to-cluster.sh
# This script helps you join the K8s-Worker-Server to the K8s-Master-Server
# 
# IMPORTANT: This is a GUIDE, not an automated script.
# You need to manually SSH into each server and run the commands.

set -euo pipefail

echo "==================================================================="
echo "Kubernetes Worker Join Guide (kubeadm-based cluster)"
echo "==================================================================="
echo ""
echo "STEP 1: SSH into K8s-Master-Server"
echo "-------------------------------------------------------------------"
echo "ssh -i /path/to/your-key.pem ec2-user@<K8S_MASTER_PUBLIC_IP>"
echo ""
echo "STEP 2: On the MASTER, verify the cluster is initialized"
echo "-------------------------------------------------------------------"
echo "kubectl get nodes"
echo "kubectl get pods -A"
echo ""
echo "STEP 3: On the MASTER, get the join command"
echo "-------------------------------------------------------------------"
echo "Option A: Use the pre-generated script (if it exists):"
echo "  cat /tmp/k8s_join_command.sh"
echo ""
echo "Option B: Generate a new join command:"
echo "  kubeadm token create --print-join-command"
echo ""
echo "The output will look like:"
echo "  sudo kubeadm join <MASTER_PRIVATE_IP>:6443 --token <TOKEN> \\"
echo "    --discovery-token-ca-cert-hash sha256:<HASH>"
echo ""
echo "STEP 4: Copy the join command from the output above"
echo "-------------------------------------------------------------------"
echo ""
echo "STEP 5: SSH into K8s-Worker-Server (in a NEW terminal)"
echo "-------------------------------------------------------------------"
echo "ssh -i /path/to/your-key.pem ec2-user@<K8S_WORKER_PUBLIC_IP>"
echo ""
echo "STEP 6: On the WORKER, run the join command (with sudo)"
echo "-------------------------------------------------------------------"
echo "Paste the command you copied from STEP 4, for example:"
echo "  sudo kubeadm join 10.0.1.100:6443 --token abcdef.1234567890abcdef \\"
echo "    --discovery-token-ca-cert-hash sha256:1234567890abcdef..."
echo ""
echo "STEP 7: Verify the worker joined (back on the MASTER)"
echo "-------------------------------------------------------------------"
echo "kubectl get nodes"
echo ""
echo "You should see both nodes:"
echo "  NAME                STATUS   ROLES           AGE   VERSION"
echo "  k8s-master-server   Ready    control-plane   10m   v1.31.x"
echo "  k8s-worker-server   Ready    <none>          1m    v1.31.x"
echo ""
echo "==================================================================="
echo "NOTES:"
echo "- Calico is already installed on the master (via k8s_master.sh)"
echo "- kubectl is only available on the master node"
echo "- Worker nodes do NOT need kubectl installed"
echo "- Use the PRIVATE IP of the master in the join command"
echo "==================================================================="
