apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/Ganil151/spring-petclinic-microservices.git
    targetRevision: main
    path: kubernetes/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-petclinic-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
