variable "project_name_1" {}
variable "vpc_id" {}
variable "subnet_cidr_block" {}
variable "vpc_cidr_block" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_cidrs" {}
variable "enable_dns_support" {}
variable "enable_dns_hostnames" {}
variable "map_public_ip_on_launch" {}
