apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: spring-petclinic-admin-server:latest
        ports:
        - containerPort: 9090
        envFrom:
        - configMapRef:
            name: spring-petclinic-common-config
        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 909080
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: spring-petclinic
spec:
  selector:
    app: admin-server
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP # In AWS/EKS, this creates an ELB
