# =============================================================================
# Ansible Inventory Generator Module
# Generates Ansible inventory from Terraform outputs
# =============================================================================

locals {
  # Generate inventory content without leading indentation
  inventory_content = <<EOT
# ─────────────────────────────────────────────────────────────────────────────
# Ansible Inventory - Auto-Generated by Terraform
# ─────────────────────────────────────────────────────────────────────────────
# Project: ${var.project_name}
# Environment: ${var.environment}
# Generated: ${timestamp()}
# 
# ⚠️  DO NOT EDIT MANUALLY - This file is auto-generated by Terraform
#    Run 'terraform apply' to update inventory after infrastructure changes
# ─────────────────────────────────────────────────────────────────────────────

[all:vars]
ansible_user=${var.ssh_user}
ansible_ssh_private_key_file=${var.ssh_key_file}
ansible_python_interpreter=/usr/bin/python3

# 🧪 Industrial Rigor: SSH Proxy Tunneling through Bastion
%{ if var.bastion_ip != "" }
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %%h:%%p -q ${var.ssh_user}@${var.bastion_ip} -i ${var.ssh_key_file} -o StrictHostKeyChecking=no"'
%{ else }
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
%{ endif }

# AWS Configuration
aws_region=${var.aws_region}
aws_account_id=${var.account_id}
vpc_id=${var.vpc_id}

# ─────────────────────────────────────────────────────────────────────────────
# CI/CD Infrastructure
# ─────────────────────────────────────────────────────────────────────────────

[jenkins_masters]
jenkins-master ansible_host=${var.jenkins_master_priv} private_ip=${var.jenkins_master_priv}

[jenkins_masters:vars]
ansible_roles=java,docker,awscli,jenkins,security_tools
jenkins_http_port=8080
jenkins_agent_port=50000

# ─────────────────────────────────────────────────────────────────────────────
# Code Quality & Security
# ─────────────────────────────────────────────────────────────────────────────

[sonarqube_servers]
sonarqube-server ansible_host=${var.sonarqube_priv} private_ip=${var.sonarqube_priv}

[sonarqube_servers:vars]
ansible_roles=java,docker,awscli,sonarqube,security_tools
sonarqube_http_port=9000

# ─────────────────────────────────────────────────────────────────────────────
# Kubernetes Worker Nodes
# ─────────────────────────────────────────────────────────────────────────────

[k8s_workers]
%{ for idx, ip in var.worker_node_priv_ips }
worker-node-${idx + 1} ansible_host=${ip} private_ip=${ip}
%{ endfor }

[k8s_workers:vars]
ansible_roles=java,docker,awscli,maven,kubectl,helm
kubernetes_role=worker

# ─────────────────────────────────────────────────────────────────────────────
# Bastion Host (Jump Box)
# ─────────────────────────────────────────────────────────────────────────────

[bastion_hosts]
%{ if var.bastion_ip != "" }
bastion-host ansible_host=${var.bastion_ip} private_ip=${var.bastion_priv_ip} ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
%{ endif }

[bastion_hosts:vars]
ansible_roles=docker,git

# ─────────────────────────────────────────────────────────────────────────────
# Environment Groups
# ─────────────────────────────────────────────────────────────────────────────

[${var.environment}_cicd:children]
jenkins_masters
sonarqube_servers

[${var.environment}_k8s:children]
k8s_workers

[${var.environment}_all:children]
${var.environment}_cicd
${var.environment}_k8s
%{ if var.bastion_ip != "" }
bastion_hosts
%{ endif }

# ─────────────────────────────────────────────────────────────────────────────
# EKS Cluster Configuration
# ─────────────────────────────────────────────────────────────────────────────

%{ if var.eks_cluster_name != "" }
[eks_clusters]
${var.eks_cluster_name}-${var.cluster_suffix} region=${var.aws_region} vpc=${var.vpc_id}
%{ endif }

# ─────────────────────────────────────────────────────────────────────────────
# Spring Petclinic Microservices
# ─────────────────────────────────────────────────────────────────────────────

[spring_petclinic:children]
${var.environment}_all

[spring_petclinic:vars]
spring_profiles_active=${var.environment}
config_server_url=http://config-server:8888
discovery_server_url=http://discovery-server:8761
EOT
}

# Generate the Ansible inventory file
resource "local_file" "ansible_inventory" {
  count    = var.enable_ansible_inventory ? 1 : 0
  filename = var.inventory_file_path
  content  = local.inventory_content

  # Ensure directory exists
  provisioner "local-exec" {
    command = "mkdir -p $(dirname ${var.inventory_file_path})"
  }
}

# Optionally run Ansible playbooks after inventory generation
resource "null_resource" "run_ansible" {
  count = var.run_ansible && var.enable_ansible_inventory ? 1 : 0

  triggers = {
    inventory_hash = local_file.ansible_inventory[0].id
  }

  provisioner "local-exec" {
    working_dir = var.ansible_working_dir
    command     = <<-EOT
      set -e
      echo "📦 Installing required Ansible collections..."
      ansible-galaxy collection install -r requirements.yml
      
      echo "🛡️ Ensuring SSH key permissions are strictly 400..."
      chmod 400 ${var.ssh_key_file}
      
      echo "🚀 Running Ansible playbooks (Industrial Rigor)..."
      ansible-playbook -i ${var.inventory_file_path} playbooks/site.yml --limit ${var.environment}_all
    EOT
  }

  depends_on = [local_file.ansible_inventory]
}

# Outputs are defined in outputs.tf
