---
mysql_root_password: "PetMa3ter$3JH3!"
mysql_petclinic_password: "Wor8erPet@12S45!"

petclinic_databases:
  - customers
  - visits
  - vets

petclinic_users:
  - name: petclinic_user
    password: "{{ mysql_petclinic_password }}"
    priv: "*.*:ALL"

# Configuration for geerlingguy.mysql role
mysql_bind_address: '0.0.0.0'
mysql_root_password_update: true

# Define databases for the role to create
mysql_databases:
  - name: customers
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: visits
    encoding: utf8mb4
    collation: utf8mb4_general_ci
  - name: vets
    encoding: utf8mb4
    collation: utf8mb4_general_ci

# Define users for the role to create
mysql_users:
  - name: petclinic_user
    password: "{{ mysql_petclinic_password }}"
    priv: "*.*:ALL"
    host: "%"

# Amazon Linux 2023 specific package configuration
mysql_daemon: mysqld
mysql_packages:
  - mysql-community-server
  - mysql-community-client

# Ensure MySQL starts on boot
mysql_enabled_on_startup: true