---
mysql_root_password: "PetMa3ter$3JH3!"
mysql_petclinic_password: "Wor8erPet@12S45!"

petclinic_databases:
  - customers
  - visits
  - vets

petclinic_users:
  - name: petclinic_user
    password: "{{ mysql_petclinic_password }}"
    priv: "*.*:ALL"