# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "petclinic-state-365269738775"
    encrypt      = true
    key          = "live/dev/vpc/terraform.tfstate"
    region       = "us-east-1"
    use_lockfile = true
  }
}
