# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"

  default_tags {
    tags = {
      Project     = "spring-petclinic"
      Environment = "live/dev/vpc"
      ManageBy    = "Gsmash-DevTeam"
      Owner       = "gsmash"
    }
  }
}
