---
# =============================================================================
# Database Credentials (FOR DEMO - ENCRYPT WITH ANSIBLE VAULT IN PROD)
# =============================================================================

db_username: "petclinic"
db_password: "PLEASE_CHANGE_ME_AND_ENCRYPT"
db_root_password: "CHANGEME_TOO"
