---
# =============================================================================
# Database Credentials (FOR DEMO - ENCRYPT WITH ANSIBLE VAULT IN PROD)
# =============================================================================

db_username: "petclinic"
db_password: "Spring$Petclinic123!"
db_root_password: "Spring$Petclinic123!"
