stage('Update Monitoring') {
    steps {
        withCredentials([
            [$class: 'SSHUserPrivateKeyBinding', credentialsId: SSH_CREDENTIALS_ID, keyFileVariable: 'SSH_KEY', usernameVariable: 'SSH_USER']
        ]) {
            script {
                echo "Updating Prometheus monitoring configuration..."
                
                sh '''
                set -e
                
                echo "=== Updating Prometheus Monitoring ==="
                echo ""
                
                # Get K8s Master IP
                K8S_MASTER_IP="${K8S_MASTER_IP}"
                if [ -z "$K8S_MASTER_IP" ]; then
                    if [ -f terraform/app/terraform.tfstate ]; then
                        K8S_MASTER_IP=$(grep -A 5 '"k8s_master"' terraform/app/terraform.tfstate | grep '"public_ip"' | head -1 | awk -F'"' '{print $4}')
                    fi
                    
                    if [ -z "$K8S_MASTER_IP" ] && [ -f ansible/inventory.ini ]; then
                        K8S_MASTER_IP=$(grep "k8s-master ansible_host" ansible/inventory.ini | awk '{print $2}' | cut -d'=' -f2)
                    fi
                fi
                
                if [ -z "$K8S_MASTER_IP" ]; then
                    echo "WARNING: Could not determine K8s Master IP, skipping Prometheus update"
                    exit 0
                fi
                
                echo "K8s Master IP: $K8S_MASTER_IP"
                echo ""
                
                # Get all service endpoints from Kubernetes
                echo "=== Discovering Kubernetes Service Endpoints ==="
                
                # Get NodePort services and their ports
                SERVICES=$(kubectl get services -o json | jq -r '.items[] | select(.spec.type=="NodePort") | "\(.metadata.name):\(.spec.ports[0].nodePort)"')
                
                if [ -z "$SERVICES" ]; then
                    echo "No NodePort services found, checking for ClusterIP services..."
                    SERVICES=$(kubectl get services -o json | jq -r '.items[] | select(.spec.type=="ClusterIP") | "\(.metadata.name):\(.spec.ports[0].port)"')
                fi
                
                echo "Discovered services:"
                echo "$SERVICES"
                echo ""
                
                # Create Prometheus scrape configuration for Kubernetes services
                echo "=== Generating Prometheus Configuration ==="
                
                cat > /tmp/prometheus-k8s-targets.yml <<'EOF'
# Kubernetes Service Discovery Configuration
# Auto-generated by Jenkins pipeline

scrape_configs:
  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  # Spring Boot Actuator endpoints (for microservices)
  - job_name: 'spring-petclinic-services'
    static_configs:
      - targets:
EOF

                # Add discovered services to Prometheus config
                echo "$SERVICES" | while IFS=: read -r service_name port; do
                    if [ -n "$service_name" ] && [ -n "$port" ]; then
                        echo "          - '${K8S_MASTER_IP}:${port}'" >> /tmp/prometheus-k8s-targets.yml
                    fi
                done
                
                cat >> /tmp/prometheus-k8s-targets.yml <<'EOF'
        labels:
          environment: 'kubernetes'
          cluster: 'petclinic-k8s'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
EOF

                echo "✓ Prometheus configuration generated"
                echo ""
                
                # Display the generated configuration
                echo "=== Generated Prometheus Configuration ==="
                cat /tmp/prometheus-k8s-targets.yml
                echo ""
                
                # Check if Prometheus is running on Docker server
                echo "=== Checking Prometheus Status ==="
                DOCKER_SERVER_IP=$(cat public_ip.txt 2>/dev/null || echo "")
                
                if [ -n "$DOCKER_SERVER_IP" ]; then
                    echo "Docker Server IP: $DOCKER_SERVER_IP"
                    SSH_OPTS="-o StrictHostKeyChecking=no -o ConnectTimeout=10 -i ${SSH_KEY}"
                    
                    # Check if Prometheus container is running
                    PROMETHEUS_RUNNING=$(ssh ${SSH_OPTS} ${SSH_USER}@${DOCKER_SERVER_IP} \
                        "docker ps --filter name=prometheus --format '{{.Names}}'" 2>/dev/null || echo "")
                    
                    if [ -n "$PROMETHEUS_RUNNING" ]; then
                        echo "✓ Prometheus container found: $PROMETHEUS_RUNNING"
                        echo ""
                        
                        # Copy the new configuration to Docker server
                        echo "=== Updating Prometheus Configuration on Docker Server ==="
                        scp ${SSH_OPTS} /tmp/prometheus-k8s-targets.yml \
                            ${SSH_USER}@${DOCKER_SERVER_IP}:/tmp/prometheus-k8s-targets.yml
                        
                        # Backup existing config and update
                        ssh ${SSH_OPTS} ${SSH_USER}@${DOCKER_SERVER_IP} bash -s <<'REMOTE'
                        set -e
                        
                        PROMETHEUS_CONFIG_DIR="/home/ec2-user/petclinic_deploy/prometheus"
                        
                        if [ -d "$PROMETHEUS_CONFIG_DIR" ]; then
                            # Backup existing configuration
                            if [ -f "$PROMETHEUS_CONFIG_DIR/prometheus.yml" ]; then
                                cp "$PROMETHEUS_CONFIG_DIR/prometheus.yml" \
                                   "$PROMETHEUS_CONFIG_DIR/prometheus.yml.backup.$(date +%Y%m%d_%H%M%S)"
                                echo "✓ Backed up existing Prometheus configuration"
                            fi
                            
                            # Append K8s targets to existing config
                            echo "" >> "$PROMETHEUS_CONFIG_DIR/prometheus.yml"
                            echo "# Kubernetes targets - auto-generated" >> "$PROMETHEUS_CONFIG_DIR/prometheus.yml"
                            cat /tmp/prometheus-k8s-targets.yml >> "$PROMETHEUS_CONFIG_DIR/prometheus.yml"
                            
                            echo "✓ Updated Prometheus configuration"
                            
                            # Reload Prometheus configuration
                            echo "Reloading Prometheus..."
                            docker exec prometheus kill -HUP 1 2>/dev/null || \
                                docker restart prometheus
                            
                            echo "✓ Prometheus reloaded successfully"
                        else
                            echo "WARNING: Prometheus config directory not found at $PROMETHEUS_CONFIG_DIR"
                        fi
REMOTE
                        
                        echo "✓ Prometheus monitoring updated on Docker server"
                    else
                        echo "ℹ Prometheus container not found on Docker server"
                        echo "  Skipping Prometheus update (optional step)"
                    fi
                else
                    echo "ℹ Docker server IP not available"
                    echo "  Skipping Prometheus update (optional step)"
                fi
                echo ""
                
                # Summary
                echo "=== Monitoring Update Summary ==="
                echo "✓ Kubernetes service endpoints discovered"
                echo "✓ Prometheus configuration generated"
                
                if [ -n "$PROMETHEUS_RUNNING" ]; then
                    echo "✓ Prometheus configuration updated and reloaded"
                    echo ""
                    echo "Prometheus URL: http://${DOCKER_SERVER_IP}:9090"
                    echo "Grafana URL: http://${DOCKER_SERVER_IP}:3000"
                else
                    echo "ℹ Prometheus update skipped (container not running)"
                fi
                echo ""
                
                echo "=== Monitoring Update Complete ==="
                '''
            }
        }
    }
}
