---
- name: Test block rescue
  block:
    - name: Task 1
      ansible.builtin.file:
        path: /tmp/test
        state: absent

    - name: Task 2
      ansible.builtin.yum_repository:
        name: test
        enabled: true
      register: result
  rescue:
    - name: Rescue task
      ansible.builtin.yum:
        name: test
        state: present
  tags: test
