[monitor]
monitor-server ansible_host=3.85.77.186 ansible_user=ec2-user

[docker]
docker-server ansible_host=3.81.67.168 ansible_user=ec2-user

[mysql]
mysql-server ansible_host=34.203.210.222 ansible_user=ec2-user

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
