apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: spring-petclinic-config-server:latest
        ports:
        - containerPort: 8888
        envFrom:
        - configMapRef:
            name: spring-petclinic-common-config
        env:
        - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
          value: "https://github.com/Ganil151/spring-petclinic-microservices-config.git" # Example URI
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 45
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: spring-petclinic
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
