apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-petclinic-common-config
  namespace: spring-petclinic
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  DISCOVERY_SERVER_URL: "http://discovery-server:8761"
  SPRING_PROFILES_ACTIVE: "docker"
  # Database Configuration (RDS)
  SPRING_DATASOURCE_URL: "jdbc:mysql://discovery-server:3306/petclinic" # Placeholder, should point to RDS endpoint
  SPRING_DATASOURCE_USERNAME: "petclinic_admin"
  # SPRING_DATASOURCE_PASSWORD: should be in a Secret
