apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customers-service
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
      - name: customers-service
        image: spring-petclinic-customers-service:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: spring-petclinic-common-config
        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "1.5Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 808180
          initialDelaySeconds: 60
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: spring-petclinic
spec:
  selector:
    app: customers-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP # In AWS/EKS, this creates an ELB
