---
# Java Role Defaults
# =============================================================================

java_version: "21"
java_distribution: "amazon"
java_home: "/usr/lib/jvm/java-21-amazon-corretto"
